config/routes.rb
get 'projects/:project_id/extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'

resources :query_categories do
  collection do
    post 'create_of_query', to: 'query_categories#create_of_query'
    post 'move_position', to: 'query_categories#move_position'
  end
end

get 'extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'
post 'extra_queries/pinning/:query_id', to: 'extra_queries#pinning'
get 'extra_queries/query_group/:query_group(/:project_id)', to: 'extra_queries#query_group'
post 'extra_queries/pinned_queries_order', to: 'extra_queries#pinned_queries_order'
resources :custom_fields do
  member do
    get 'ajax_options'
  end
end

app/models/query_category.rb
class QueryCategory < ActiveRecord::Base
  has_many :query, foreign_key: :category_id, dependent: :nullify
  belongs_to :user, foreign_key: :author_id

  attr_protected :id
end

app/controllers/query_categories_controller.rb
class QueryCategoriesController < ApplicationController
  before_filter :require_login
  before_filter :authorized_globaly?
  before_filter :find_query_category, except: [:index, :new, :create, :create_of_query, :move_position]

  def index
    @query_categories = QueryCategory.order(:position)
  end

  def new
    @query_category = QueryCategory.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def update
    @query_category.update_attributes(params[:query_category])
  end

  def create
    @query_category = QueryCategory.create(name: params[:query_category][:name], author_id: User.current.id, position: QueryCategory.order(:position).last.try(:position).to_i + 1)
  end

  def create_of_query
    category = QueryCategory.create(name: params[:name], author_id: User.current.id, position: QueryCategory.order(:position).last.try(:position).to_i + 1)
    render json: { id: category.id, name: category.name }
  end

  def move_position
    qc = QueryCategory.find(params[:query_category_id])
    if params[:new_position].to_i + 1 > qc.position
      QueryCategory.where('position > ? and position <= ?', qc.position, params[:new_position].to_i + 1).update_all('position = position - 1')
    elsif params[:new_position].to_i + 1 < qc.position
      QueryCategory.where('position < ? and position >= ?', qc.position, params[:new_position].to_i + 1).update_all('position = position + 1')
    end
    qc.update_attributes(position: params[:new_position].to_i + 1)

    if request.xhr?
      render nothing: true
      return
    end

    redirect_to action: 'index'
  end

  def destroy
    @query_category.destroy
  end

  private

  def find_query_category
    @query_category = QueryCategory.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/views/query_categories/_form.html.erb
<%= form_for @query_category , remote: true, id: 'query-category-form' do |f| %>
    <div class="modal-body">
        <h2><%= @query_category.new_record? ? l(:eq_label_new_query_category) : l(:eq_label_query_categories) %></h2>
        <div>
          <%= f.label(:name, (l(:field_name)+content_tag(:span, ' *', :class => 'required')).html_safe) %>
          <br>
          <%= f.text_field :name, style: 'width: 100%; max-width: 100%;' %>
        </div>
        <br>
        <% if @query_category.query.any? %>
            <div>
              <p><%= l(:eq_dependent_query) %>: <%= @query_category.query.map {|q| q.name}.join(', ') %></p>
            </div>
        <% end %>
    </div>
    <div class="modal-footer">
      <%= f.submit( l(:button_save), style: 'margin: 0px;') %>
      <button class="" data-dismiss="modal" aria-hidden="true" style="vertical-align: middle;"><%= l(:lib_close) %></button>
    </div>
<% end %>

app/views/query_categories/_one_query_category.html.erb
<tr id="query-category-<%= qc.id %>">
  <td class="H"><%= qc.name %></td>
  <td class="H"><%= link_to_user(qc.user) %></td>
  <td class="H" style="text-align:right; padding-right: 5px; width: 1px;">
    <nobr>
      <%= link_to( content_tag(:span,l(:button_edit)),
                   {controller: 'query_categories', action: 'edit', id: qc.id},
                   remote: true,
                   class: 'icon icon-edit in_link eq_ajax_edit',
                   data: {target: 'query_categories_form'}) %>
      <%= link_to( content_tag(:span,l(:button_delete)),
                   {controller: 'query_categories', action: 'destroy', id: qc.id},
                   class: 'icon icon-del in_link',
                   method: :delete,
                   remote: true,
                   data: { confirm: l(:confirm_delete_query_category) }) %>
    </nobr>
  </td>
</tr>

app/views/query_categories/create.js.erb
$('#query_categories_form').modal('hide');
$('<%= escape_javascript(render partial: 'one_query_category',  locals: {qc: @query_category} ) %>').appendTo('#content > div.autoscroll > table > tbody');
$('#query-category-<%= @query_category.id %>').effect('highlight', 500);
$("#query-category-<%= @query_category.id %>").append("<td class='ordered-hndl'> ≡ </td>");
$("div.autoscroll > .list > tbody").sortable( "refresh" );

app/views/query_categories/destroy.js.erb
$('#query-category-<%= @query_category.id %>').remove();
$('#query_categories_form').modal('hide');
$("div.autoscroll > .list > tbody").sortable( "refresh" );

app/views/query_categories/index.html.erb
<% heads_for_wiki_formatter %>

<div class="contextual">
  <%= link_to l(:eq_label_new_query_category), new_query_category_path, class: 'icon icon-add in_link eq_ajax_edit', data: {target: 'query_categories_form'} %>
</div>

<h2><%= l(:eq_label_query_categories) %></h2>

<% if @query_categories.any? %>
    <div class="autoscroll">
      <table class="list">

        <thead>
            <tr>
              <th><%= l(:field_name) %></th>
              <th><%= l(:field_author) %></th>
              <th>&nbsp;</th>
            </tr>
        </thead>

        <tbody>
            <% @query_categories.each do |qc| %>
                <%= render partial: 'one_query_category', locals: {qc: qc} %>
            <% end %>
        </tbody>

      </table>
    </div>
<% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<div id="query_categories_form" class="modal I fade" tabindex="-1" role="dialog" aria-hidden="true" data-width="500px" data-height="90%" style="z-index: 1060;"></div>

<script type="text/javascript" charset="utf-8">
    $(document.body).on('click', '.eq_ajax_edit', function () {
        var form_div = $('#'+$(this).attr('data-target'));
        form_div.html('<div class="loader form_loader"></div>');
        form_div.modal('show');
        form_div.load(this.href, function () {
            RMPlus.LIB.resize_bs_modal(form_div);
        });
        return false;
    });


    $("div.autoscroll > .list > thead > tr").append("<th></th>");
    $("div.autoscroll > .list > tbody tr").append("<td class='ordered-hndl'> ≡ </td>");
    $("div.autoscroll > .list > tbody").sortable({
        cursor: 'move',
        opacity: 0.6,
        handle: '.ordered-hndl',
        helper: function(e, tr) {
            var cl = tr.clone();
            cl.height(tr.outerHeight() - 1);
            cl.css({ padding: 0, borderTop: '#ccc solid 1px', borderLeft: '#ccc solid 1px' });
            var $originals = tr.children();
            cl.children().each(function(index) {
                $(this).width($originals.eq(index).width() + 1);
            });
            return cl;
        },
        update: function(event, ui){
            $.ajax({
                type: 'POST',
                data: {query_category_id: ui.item.find('a[data-method="delete"]').attr('href').split('/').pop() ,new_position: ui.item.index()},
                url: RMPlus.Utils.relative_url_root + '/query_categories/move_position'
            });
        }
    })

</script>

app/views/query_categories/update.js.erb
$('#query_categories_form').modal('hide');
var prev_tr = $('#query-category-<%= @query_category.id %>').prev('tr');
$('#query-category-<%= @query_category.id %>').remove();
if(prev_tr.length == 0){
    $('<%= escape_javascript(render partial: 'one_query_category',  locals: {qc: @query_category} ) %>').prependTo($('#content').find('> div.autoscroll > table > tbody'));
}else{
    $('<%= escape_javascript(render partial: 'one_query_category',  locals: {qc: @query_category} ) %>').insertAfter(prev_tr);
}

$('#query-category-<%= @query_category.id %>').effect('highlight', 500);
$("#query-category-<%= @query_category.id %>").append("<td class='ordered-hndl'> ≡ </td>");
$("div.autoscroll > .list > tbody").sortable( "refresh" );