config/routes.rb
get 'projects/:project_id/extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'

resources :query_categories do
  collection do
    post 'create_of_query', to: 'query_categories#create_of_query'
    post 'move_position', to: 'query_categories#move_position'
  end
end

get 'extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'
post 'extra_queries/pinning/:query_id', to: 'extra_queries#pinning'
get 'extra_queries/query_group/:query_group(/:project_id)', to: 'extra_queries#query_group'
post 'extra_queries/pinned_queries_order', to: 'extra_queries#pinned_queries_order'
resources :custom_fields do
  member do
    get 'ajax_options'
  end
end

app/controllers/extra_queries_controller.rb
class ExtraQueriesController < ApplicationController
  before_filter :find_optional_project, only: [:add_filter]

  include IssuesHelper
  helper :issues_extend

  def add_filter
    @fields = params[:fields]

    if params[:query_id].present?
      @query = IssueQuery.find(params[:query_id])
    else
      @query = Query.new_subclass_instance(params[:type] || 'IssueQuery', { project: @project, name: '_' })
    end

    if @project.present?
      @query.project = @project
    end
  end

  def pinning
    @query = IssueQuery.find(params[:query_id])
    if params[:pin]
      @query.eq_user_pinned_query ||= EqPinnedQuery.new(user_id: User.current.id, position: EqPinnedQuery.where(user_id: User.current.id).order("#{EqPinnedQuery.table_name}.position desc").first.try(:position).to_i + 1)
    else
      @query.eq_user_pinned_query.try(:destroy)
    end
  end

  def query_group
    @project = Project.find(params[:project_id]) if params[:project_id]
    if params[:query_group] == 'queries'
      session[:eq_queries_expanded] = params[:status]
    elsif params[:query_group] == 'categories'
      session[:eq_queries_by_category_expanded] = params[:status]
    elsif params[:query_group] == 'queries_by_role'
      session[:eq_queries_by_role_expanded] = params[:status]
    end

    if params[:expand]
      render layout: false
    else
      render nothing: true
    end
  end

  def pinned_queries_order
    queries_ids = params['pinned-query']
    queries = IssueQuery.preload(:eq_user_pinned_query).where(id: queries_ids + [0]).to_a
    queries_ids.each_with_index do |q, index|
      q = queries.select { |it| it.id == q.to_i }.first
      next unless (q)
      q.eq_user_pinned_query ||= EqPinnedQuery.new(user_id: User.current.id)
      q.eq_user_pinned_query.position = index
      q.eq_user_pinned_query.save
    end

    render nothing: true
  end

  private

  def sidebar_queries(query_type)
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?

  end

  def find_optional_project
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/views/extra_queries/queries/_filters.html.erb
<% @query.sort_criteria = @query.sort_criteria.blank? ? (@query.is_a?(IssueQuery) ? [['id', 'asc']] : [['spent_on', 'desc']]) : @query.sort_criteria %>

<script type="text/javascript">
  $('#query_form_with_buttons').hide();
  RMPlus.EQ.query_class = '<%= @query.class.name %> ';
  RMPlus.EQ.custom_query_page_enabled = <%= Setting.plugin_extra_queries['custom_query_page_enabled'] ? 1 : 0 %>;
  RMPlus.EQ.custom_query_timelog_page_enabled = <%= Setting.plugin_extra_queries['custom_query_timelog_page_enabled'] ? 1 : 0 %>;
  RMPlus.EQ.label_and = '<%= l(:eq_label_and) %>';
  RMPlus.EQ.label_delete_filter = '<%= l(:eq_label_delete_filter) %>';
  RMPlus.EQ.label_save_button = '<%= l(:button_save) %>';
  RMPlus.EQ.label_cancel_button = '<%= l(:button_cancel) %>';
  RMPlus.EQ.sort_label = '<%= l(:eq_label_sort) %>';
  RMPlus.EQ.standalone_operators = <%= get_enabled_filters([]).to_json.html_safe %>;

  RMPlus.EQ.saved_data = <%= (@query.filters || {}).inject({}) { |res, (k, v)| v[:values] = Array.wrap(v[:values]); res[k] ||= { e: v[:operator], v: v[:values] }; res; }.to_json.html_safe %>;
  RMPlus.EQ.saved_data = RMPlus.EQ.saved_data || {};
  RMPlus.EQ.saved_data['fields-list'] = <%= { e: '', v: (@query.filters || {}).keys }.to_json.html_safe %>;
  <% sort = @query.sort_criteria || [] %>
  <% sort.each_with_index do |srt, index| %>
    RMPlus.EQ.saved_data['sort_by_<%= index %>'] = { e: '<%= srt[1] %>', v: ['<%= srt[0] %>'] };
  <% end %>
  RMPlus.EQ.saved_data['group_by'] = <%= { e: '', v: @query.group_by.present? ? [@query.group_by] : [] }.to_json.html_safe %>;
  RMPlus.EQ.saved_data['show'] = <%= { e: '', v: @query.available_block_columns.select { |it| @query.has_column?(it) }.map { |it| it.name.to_s } }.to_json.html_safe %>;
  <% if Redmine::Plugin.installed?(:clear_plan) && @query.is_a?(IssueQuery) %>
    RMPlus.EQ.saved_data['cp_burndown'] = <%= { e: '', v: (@query.cp_burndown || []).compact }.to_json.html_safe %>;
  <% end %>
  <% if Redmine::VERSION.to_s >= '3.2.0' %>
    RMPlus.EQ.saved_data['totalable'] = <%= { e: '', v: @query.totalable_names.present? ? @query.totalable_names : [] }.to_json.html_safe %>
  <% end %>

  RMPlus.EQ.query_form_content_html = '<%= escape_javascript(render(partial: 'extra_queries/filters', locals: { query: @query })) %>';
  RMPlus.EQ.buttons_html = '<%= escape_javascript((render(partial: "#{controller_name}/eq_filter_buttons", locals: { query: @query, project: @project }) rescue '')) %>';

  RMPlus.EQ.project_id = '<%= params[:project_id] %>';
  RMPlus.EQ.saved_query_id = <%= (query.id || params[:saved_query_id]).to_i %>;
</script>

app/views/extra_queries/queries/_form.html.erb
<div class="modal-header">
  <a href="#" class="fa fa-times eq-no-line eq-close" data-dismiss="modal" aria-hidden="true"></a>
  <h3><%= @query.new_record? ? l(:label_query_new) : @query.name %></h3>
</div>
<div class="modal-body">
  <%= error_messages_for @query %>

  <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>
  <%= hidden_field_tag 'cp_burndown', '1' if params[:cp_burndown] %>

  <% (@query.filters || {}).each do |k, f| %>
    <%= hidden_field_tag 'f[]', k %>
    <%= hidden_field_tag "op[#{k}]", f[:operator] %>
    <% f[:values] = [f[:values]] if (f[:values].present? || f[:values] == '') && !f[:values].is_a?(Array) %>
    <% (f[:values] || []).each do |v| %>
      <%= hidden_field_tag "v[#{k}][]", v %>
    <% end %>
  <% end %>

  <% (@query.sort_criteria || []).each_with_index do |sort, index| %>
    <%= hidden_field_tag "query[sort_criteria][#{index}][]", sort[0] %>
    <%= hidden_field_tag "query[sort_criteria][#{index}][]", sort[1] %>
  <% end %>

  <% if @query.group_by.present? %>
    <%= hidden_field_tag 'query[group_by]', @query.group_by %>
  <% end %>

  <% (@query.column_names || []).each do |col| %>
    <%= hidden_field_tag 'c[]', col %>
  <% end %>

  <table class="plugin_settings" style="width: 100%">
    <tr>
      <td>
        <label for="query_name"><%=l(:field_name)%></label>
      </td>
      <td>
        <%= text_field 'query', 'name', size: 80 %>
      </td>
    </tr>
    <tr>
      <td>
        <label for="query_category_id"><%= l(:eq_label_query_category) %></label>
      </td>
      <td>
        <%= select_tag('query[category_id]', options_for_select([[]] + QueryCategory.order('name').map { |c| [c.name, c.id] }, @query.category_id), class: 'select2 eq-select2', 'data-combobox' => 'true', 'data-post-url' => Redmine::Utils.relative_url_root + '/query_categories/create_of_query', 'data-model-attribute' => 'name', 'data-select2-width' => '400px') %>
      </td>
    </tr>
    <% if Setting.plugin_extra_queries['custom_query_sidebar_enabled'] && User.current.admin? %>
      <tr>
        <td></td>
        <td>
          <label for="query_eq_pinned">
            <%= check_box_tag('query[eq_pinned]', '1', @query.eq_admin_pinned?) %>
            &mdash;
            <%= l(:eq_label_admin_pin_query) %>
          </label>
        </td>
      </tr>
    <% end %>
    <% if Redmine::Plugin.installed?(:ajax_counters) && Setting.plugin_extra_queries['custom_query_counter_enabled'] && User.current.admin? %>
        <tr>
          <td></td>
          <td>
            <label for="query_eq_counter">
              <%= hidden_field_tag('query[eq_counter]', false) %>
              <%= check_box_tag('query[eq_counter]', true, @query.eq_counter) %>
              &mdash;
              <%= l(:eq_show_query_counter) %>
            </label>
          </td>
        </tr>
    <% end %>
    <% if User.current.admin? || User.current.allowed_to?(:manage_public_queries, @query.project) %>
      <tr>
        <td>
          <label><%= l(:field_visible) %></label>
        </td>
        <td>
          <div style="margin-bottom: 5px">
            <label style="display: block;"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
            <label style="display: block;"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
            <label style="display: block;"><%= radio_button 'query', 'visibility', Query::VISIBILITY_ROLES %> <%= l(:label_visibility_roles) %>:</label>
          </div>
          <div id="eq-roles-list">
            <div class='eq-filter-data'>
              <div class="eq-filter-data-list eq-filter-data-item">
                <%= eq_filter_selector(Role.givable.sorted.map { |r| [r.name, r.id] }, selected: @query.roles.map { |it| it.id.to_s }, fullname: 'query[role_ids][]', class: 'eq-columns-list') %>
                <%= hidden_field_tag 'query[role_ids][]', '' %>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td>
        <label for="query_is_for_all">
          <%= check_box_tag 'query_is_for_all', 1, @query.project.nil?, class: (User.current.admin? ? '' : 'disable-unless-private') %>
          &mdash;
          <%= l(:field_is_for_all) %>
        </label>

        <div id="eq-hide-in-projects" style="padding-top: 10px;<%= ' display: none;'.html_safe unless @query.project.nil? %>">
          <%= l(:eq_label_hide_query_for_projects) %>
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(Project.active.order(:name).map { |r| [r.name, r.id] }, selected: @query.eq_hide_in_project_ids, fullname: 'query[hide_in_projects][]', class: 'eq-columns-list') %>
              <%= hidden_field_tag 'query[hide_in_projects][]', '' %>
            </div>
          </div>
        </div>

        <div id="eq-show-in-projects" style="padding-top: 10px;<%= ' display: none;'.html_safe unless @query.project.nil? %>">
          <%= l(:eq_label_show_query_for_projects) %>
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(Project.active.order(:name).map { |r| [r.name, r.id] }, selected: @query.eq_show_in_project_ids, fullname: 'query[show_in_projects][]', class: 'eq-columns-list') %>
              <%= hidden_field_tag 'query[show_in_projects][]', '' %>
            </div>
          </div>
        </div>

        <div id="with_sub_project" style="padding-top: 10px;<%= ' display: none;'.html_safe unless @query.project.nil? %>">
          <label for="query_sub_project">
            <%= check_box_tag 'query[sub_project]', true, @query.sub_project, class: (User.current.admin? ? '' : 'disable-unless-private') %>
            &mdash;
            <%= l(:label_cross_project_descendants) %>
          </label>
        </div>
      </td>
    </tr>

    <tr class="rmp-settings-group">
      <td></td>
      <td>
        <%= l(:label_options) %>
      </td>
    </tr>
    <% if Redmine::Plugin.installed?(:rm_business_time) && params[:cp_burndown].present? %>
      <tr>
        <td></td>
        <td>
          <label>
            <%= check_box_tag 'query[cp_burndown][]', 'cp_burndown_work_off', (@query.cp_burndown || []).include?('cp_burndown_work_off') %>
            &mdash;
            <%= l(:cp_label_burndown_apply_work_off) %>
          </label>
        </td>
      </tr>
    <% end %>

    <% if params[:gantt] %>
      <tr>
        <td>
          <label><%= l(:button_show) %></label>
        </td>
        <td>
          <label class="inline"><%= check_box_tag "query[draw_relations]", "1", @query.draw_relations %> &mdash; <%= t(:label_related_issues) %></label>
          <label class="inline"><%= check_box_tag "query[draw_progress_line]", "1", @query.draw_progress_line %> &mdash; <%= l(:label_gantt_progress_line) %></label>
        </td>
      </tr>
    <% elsif @query.new_record? %>
      <tr>
        <td></td>
        <td>
          <label for="query_default_columns">
            <%= hidden_field_tag 'default_columns', 1 if params[:cp_burndown].present? %>
            <%= check_box_tag 'default_columns', 1, @query.has_default_columns? || params[:cp_burndown].present?, id: 'query_default_columns', disabled: params[:cp_burndown].present? %>
            &mdash;
            <%= l(:label_default_columns) %>
          </label>
        </td>
      </tr>
    <% end %>
    <% if Redmine::Plugin.installed?(:magic_my_page) %>
      <tr>
        <td><%= l(:label_mmp_legend_for_edit_queries) %></td>
        <td>
          <table>
            <tr>
              <td id="eq-mmp-available-columns">
                <%= l(:description_available_columns) %>
                <%
                   available_columns = eq_query_available_inline_columns_options_for_mm_page(@query)
                   available_columns = query_available_inline_columns_options(@query) if available_columns == []

                   selected_columns = eq_query_selected_inline_columns_options_for_mm_page(@query)
                   selected_columns = query_selected_inline_columns_options(@query) if selected_columns == []

                   available_columns = available_columns - selected_columns
                %>
                <div class='eq-filter-data'>
                  <div class="eq-filter-data-list eq-filter-data-item">
                    <%= eq_filter_selector(available_columns.sort { |x,y| (x[0] || '') <=> (y[0] || '') }, fullname: 'mmp_column_names[]', class: 'eq-columns-list eq-available-columns-container') %>
                  </div>
                </div>
              </td>
              <td style="vertical-align: middle; box-sizing: border-box;">
                <p>
                  <%= link_to('&#8594;'.html_safe, '#', class: 'eq-button eq-add-column', style: 'margin-bottom: 5px;') %>
                </p>
                <p>
                  <%= link_to('&#8592;'.html_safe, '#', class: 'eq-button eq-delete-column') %>
                </p>
              </td>
              <td id="eq-mmp-selected-columns">
                <%= l(:description_selected_columns) %>
                <div class='eq-filter-data'>
                  <div class="eq-filter-data-list eq-filter-data-item">
                    <%= eq_filter_selector(selected_columns, class: 'eq-columns-list eq-columns-container', fullname: 'mmp_column_names[]', id: 'eq-mmp-columns-container') %>
                  </div>
                </div>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    <% end %>
  </table>

</div>
<div class="modal-footer">
  <%= submit_tag l(:button_save), onclick: "$('#eq-mmp-selected-columns [name=\"mmp_column_names[]\"]').prop('checked', true);" %>
  <button aria-hidden="true" data-dismiss="modal" style="vertical-align: middle;"><%= l(:eq_label_close_window) %></button>
</div>


<script>
  $(document).ready(function(){
    $("input[name='query[visibility]']").change(function(){
      var roles_checked = $('#query_visibility_1').is(':checked');
      var private_checked = $('#query_visibility_0').is(':checked');
      $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !roles_checked);
      if (!private_checked) $("input.disable-unless-private").attr('checked', false);
      $("input.disable-unless-private").attr('disabled', !private_checked);
    }).trigger('change');
  });
  $('#eq-roles-list, #eq-mmp-available-columns, #eq-mmp-selected-columns, #eq-hide-in-projects, #eq-show-in-projects').eq_button({ just_search: true });

  $('#query_is_for_all').change(function() {
    if (this.checked) {
      $('#eq-hide-in-projects').show();
      $('#eq-show-in-projects').show();
      $('#with_sub_project').show();
    } else {
      $('#eq-hide-in-projects').hide();
      $('#eq-show-in-projects').hide();
      $('#with_sub_project').hide();
    }
  });

  RMPlus.Utils.makeSelect2Combobox($('#query_category_id').get(0));
</script>

app/views/extra_queries/queries/edit.html.erb
<%= form_tag(query_path(@query), method: :put, remote: true) do %>
  <%= render partial: 'form' %>
<% end %>

app/views/extra_queries/queries/edit.js.erb
<% if @query.errors.present? %>
  $('#content').find('.flash').remove();
  $('#errorExplanation').remove();

  $('#eq-query-modal').find('.modal-body').prepend('<%= escape_javascript(error_messages_for(@query)) %>');
<% end %>

app/views/extra_queries/queries/new.html.erb
<%= form_tag(@project ? project_queries_path(@project) : queries_path, remote: true) do %>
  <%= render partial: 'form' %>
<% end %>

app/views/extra_queries/queries/new.js.erb
<% if @query.errors.present? %>
  $('#content').find('.flash').remove();
  $('#errorExplanation').remove();

  $('#eq-query-modal').find('.modal-body').prepend('<%= escape_javascript(error_messages_for(@query)) %>');
<% else %>
  $('div.loader').html(' ');
  $(document.body).removeData('ajax_emmiter');
  $('#eq-query-modal').find('input[type="submit"]').removeClass('ajax_hidden_emmiter');


  window.location.href = '<%= eq_redirect_to_issues_path(query_id: @query.id) %>';
<% end %>