config/routes.rb
get 'projects/:project_id/extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'

resources :query_categories do
  collection do
    post 'create_of_query', to: 'query_categories#create_of_query'
    post 'move_position', to: 'query_categories#move_position'
  end
end

get 'extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'
post 'extra_queries/pinning/:query_id', to: 'extra_queries#pinning'
get 'extra_queries/query_group/:query_group(/:project_id)', to: 'extra_queries#query_group'
post 'extra_queries/pinned_queries_order', to: 'extra_queries#pinned_queries_order'
resources :custom_fields do
  member do
    get 'ajax_options'
  end
end

app/controllers/extra_queries_controller.rb
class ExtraQueriesController < ApplicationController
  before_filter :find_optional_project, only: [:add_filter]

  include IssuesHelper
  helper :issues_extend

  def add_filter
    @fields = params[:fields]

    if params[:query_id].present?
      @query = IssueQuery.find(params[:query_id])
    else
      @query = Query.new_subclass_instance(params[:type] || 'IssueQuery', { project: @project, name: '_' })
    end

    if @project.present?
      @query.project = @project
    end
  end

  def pinning
    @query = IssueQuery.find(params[:query_id])
    if params[:pin]
      @query.eq_user_pinned_query ||= EqPinnedQuery.new(user_id: User.current.id, position: EqPinnedQuery.where(user_id: User.current.id).order("#{EqPinnedQuery.table_name}.position desc").first.try(:position).to_i + 1)
    else
      @query.eq_user_pinned_query.try(:destroy)
    end
  end

  def query_group
    @project = Project.find(params[:project_id]) if params[:project_id]
    if params[:query_group] == 'queries'
      session[:eq_queries_expanded] = params[:status]
    elsif params[:query_group] == 'categories'
      session[:eq_queries_by_category_expanded] = params[:status]
    elsif params[:query_group] == 'queries_by_role'
      session[:eq_queries_by_role_expanded] = params[:status]
    end

    if params[:expand]
      render layout: false
    else
      render nothing: true
    end
  end

  def pinned_queries_order
    queries_ids = params['pinned-query']
    queries = IssueQuery.preload(:eq_user_pinned_query).where(id: queries_ids + [0]).to_a
    queries_ids.each_with_index do |q, index|
      q = queries.select { |it| it.id == q.to_i }.first
      next unless (q)
      q.eq_user_pinned_query ||= EqPinnedQuery.new(user_id: User.current.id)
      q.eq_user_pinned_query.position = index
      q.eq_user_pinned_query.save
    end

    render nothing: true
  end

  private

  def sidebar_queries(query_type)
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?

  end

  def find_optional_project
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/views/extra_queries/issues/_eq_filter_buttons.html.erb
<%= link_to l(:button_apply), project ? project_issues_path(project) : issues_path, class: 'eq-button eq-button-success', id: 'eq-apply-query' %>
<%= link_to l(:button_clear), { set_filter: 1, project_id: project }, class: 'eq-button' %>
<% if User.current.allowed_to?(:save_queries, project, global: true) %>
  <%= link_to l(:eq_label_save_as), new_query_path(_a: 1, project_id: project), class: 'eq-button', id: 'eq-query-save-as' %>
<% end %>

<% if !query.new_record? && query.editable_by?(User.current) %>
  <%= link_to l(:eq_label_save), edit_query_path(query, _a: 1), class: 'eq-button', id: 'eq-query-save' %>
  <%= delete_link query_path(query), class: 'eq-button' %>
<% end %>

app/views/extra_queries/issues/_eq_filter_params.html.erb
<fieldset id="eq-filter-params" class="collapsible collapsed">
  <legend onclick="toggleFieldset(this);"><%= l(:eq_label_options) %></legend>
  <div style="display: none;">
    <div class="eq-panel eq-sort-items">
      <% (query.sort_criteria || [['id', 'asc']]).each_with_index do |srt, index| %>
        <%= link_to '', '#', class: 'eq-another-button', id: "f-sort_by_#{index}", title: l(:eq_label_sort), data: { field: "sort_by_#{index}" } %>

        <div class='modal_window eq-filter-field' id='modal-f-sort_by_<%= index %>' style="padding-top: 10px;">
          <div class="eq-filter-operator">
            <%= select_tag('sort_direction[]', options_for_select([[l(:label_ascending),'asc'],[l(:label_descending),'desc']], srt[1]), class: 'eq-operator') %>
          </div>
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item" data-operators="asc,desc">
              <%= eq_filter_selector(query.available_columns.select(&:sortable?).sort_by(&:caption).collect { |column| [column.caption, column.name.to_s] }.sort { |x,y| (x[0] || '') <=> (y[0] || '') }, radio: true, name: "sort-#{index}") %>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to "<span>#{l(:eq_label_add_sort)}</span>".html_safe, '#', class: 'rm-icon fa-plus no_line in_link', id: 'eq-add-sort', style: (query.sort_criteria || []).size >= 3 ? 'display:none;' : nil %>
    </div>


    <div class="eq-panel">
      <% if query.groupable_columns.present? %>
        <%= link_to '', '#', class: 'eq-another-button', id: 'f-group_by', title: l(:eq_label_group), data: { field: 'group_by' } %>
        <div class='modal_window eq-another-list' id='modal-f-group_by' style="padding-top: 10px;">
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(query.groupable_columns.collect { |c| [c.caption, c.name.to_s] }.sort { |x,y| (x[0] || '') <=> (y[0] || '') }, radio: true, name: 'group') %>
            </div>
          </div>
        </div>
      <% end %>

      <% if Redmine::VERSION.to_s >= '3.2.0' && query.available_totalable_columns.present? %>
        <%= link_to '', '#', class: 'eq-another-button', id: 'f-totalable', title: l(:label_total_plural), data: { field: 'totalable' } %>
        <div class='modal_window eq-another-list' id='modal-f-totalable' style="padding-top: 10px;">
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(query.available_totalable_columns.collect { |c| [c.caption, c.name.to_s] }.sort { |x,y| (x[0] || '') <=> (y[0] || '') }) %>
            </div>
          </div>
        </div>
      <% end %>

      <% if query.available_block_columns.present? %>
        <%= link_to '', '#', class: 'eq-another-button', id: 'f-show', title: l(:button_show), data: { field: 'show' } %>
        <div class='modal_window eq-another-list' id='modal-f-show' style="padding-top: 10px;">
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(query.available_block_columns.map { |it| [it.caption.to_s, it.name.to_s] }.sort { |x,y| (x[0] || '') <=> (y[0] || '') }) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="eq-panel" style="margin-bottom: 0;">
      <table>
        <tr>
          <td id="eq-available-fields">
            <%= l(:description_available_columns) %>
            <div class='eq-filter-data'>
              <div class="eq-filter-data-list eq-filter-data-item">
                <%= eq_filter_selector(query_available_inline_columns_options(query).sort { |x,y| (x[0] || '') <=> (y[0] || '') }, class: 'eq-columns-list eq-available-columns-container') %>
              </div>
            </div>
          </td>
          <td style="box-sizing: border-box;">
            <p>
              <%= link_to('&#8594;'.html_safe, '#', class: 'eq-button eq-add-column', style: 'margin-bottom: 5px;') %>
            </p>
            <p>
              <%= link_to('&#8592;'.html_safe, '#', class: 'eq-button eq-delete-column') %>
            </p>
          </td>
          <td id="eq-selected-fields">
            <%= l(:description_selected_columns) %>
            <div class='eq-filter-data'>
              <div class="eq-filter-data-list eq-filter-data-item">
                <%= eq_filter_selector(query_selected_inline_columns_options(query), class: 'eq-columns-list eq-columns-container', id: 'eq-columns-container') %>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
</fieldset>